### ISSUE TITLE
Crash on CheckBaseObject 

### ISSUE THREAD

**Issue by rshkarin** [megamarc/Tilengine#15]
Hello,

I have tried to run sample mosaic.py, but it crashes with the following backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5de62b5 in CheckBaseObject () from /usr/lib/x86_64-linux-gnu/libTilengine.so
(gdb) backtrace
#0  0x00007ffff5de62b5 in CheckBaseObject () from /usr/lib/x86_64-linux-gnu/libTilengine.so
#1  0x00007ffff5de6c55 in TLN_GetSequence () from /usr/lib/x86_64-linux-gnu/libTilengine.so
#2  0x00007ffff6284ec0 in ffi_call_unix64 () from /home/user/anaconda2/lib/python2.7/lib-dynload/../../libffi.so.6
#3  0x00007ffff628487d in ffi_call () from /home/user/anaconda2/lib/python2.7/lib-dynload/../../libffi.so.6
#4  0x00007ffff649a736 in _ctypes_callproc () from /home/user/anaconda2/lib/python2.7/lib-dynload/_ctypes.so
#5  0x00007ffff6490a61 in PyCFuncPtr_call () from /home/user/anaconda2/lib/python2.7/lib-dynload/_ctypes.so
```

**Comment by megamarc** [comment]
Seems that the updated binding which introduces automatic garbage management causes some problems in linux. Maybe objects get destroyed when they're still in their valid life cycle, causing the binary to crash. Tested the underlying library with the C samples in linux and they work as expected, so the problem is in the new python binding itself. The same binding under windows work as expected.
