### ISSUE TITLE
C# sample attempted to read or write protected memory.

### ISSUE THREAD

**Issue by CybertronicToon** [megamarc/Tilengine#31]
Whenever I run the C# sample, it gives me the following error:

> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Tilengine.Window.TLN_DrawFrame(Int32 time)
   at Tilengine.Window.DrawFrame(Int32 time) in c:\Users\Dallas\Downloads\Tilengine_windows_win32\samples\csharp\Tilengine.cs:line 808
   at Platformer.Main(String[] args) in c:\Users\Dallas\Downloads\Tilengine_windows_win32\samples\csharp\Platformer.cs:line 116

I copy-pasted tilengine.dll, because it is required. Also, I am using SharpDevelop.

**Comment by megamarc** [comment]
Fixed in binding CsTilengine sister project: https://github.com/megamarc/CsTilengine/commit/b8467ab6c897170511706123f17793fddf2608b1
