### ISSUE TITLE
Just can't get the examples to load

### ISSUE THREAD

**Issue by CyborgCabbage** [megamarc/Tilengine#34]
For all of the examples I get this message:
```
Traceback (most recent call last):
  File "mode7.py", line 6, in <module>
    from tilengine import *
  File "C:\Users\Finlay Laidlaw\Desktop\Tilengine\samples\python\tilengine.py", line 271, in <module>
    _tln = cdll.LoadLibrary("Tilengine.dll")
  File "C:\Users\Finlay Laidlaw\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Finlay Laidlaw\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
I'm running Python 3.7 on Windows 10 64-bit
Please help me out, I'm relatively new to python and not very good at debugging.

**Comment by megamarc** [comment]
Hi,
It seems that Tilengine.dll and SDL2.dll are not located inside the "python" samples directory. They should They're not distributed as precompiled binaries in GitHub, if you want them you should grab them from itch.io page in tilengine (https://megamarc.itch.io/tilengine) and download for Windows 64-bit. Or build yourself from source, either way. Then copy Tilengine.dll and SDL2.dll to the python samples folder and they should work

**Comment by megamarc** [comment]
For support questions that aren't feature requests or bugs is better to go to the official forums:
http://www.tilengine.org/forum/index.php
